global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 35
  height: 35
  origin_x: -17.5
  origin_y: -17.5
  static_map: true
  rolling_window: true
  inflation_radius: 0.5
  resolution: 0.1
