local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 9
  height: 9
  origin_x: -4.5
  origin_y: -4.5
  resolution: 0.05
  inflation_radius: 0.2
