TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.06
  max_vel_theta: 3.8
  min_vel_theta: -3.8
  min_in_place_vel_theta: 0.15

  acc_lim_theta: 0.25
  acc_lim_x: 0.5
  acc_lim_Y: 0.3

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25

  pdist_scale: 3.5
  gdist_scale: 1.0
  occdist_scale: 2.0
